// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/gateway/v1/gateway_model.proto

package gateway_v1

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StringArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []string               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringArray) Reset() {
	*x = StringArray{}
	mi := &file_api_gateway_v1_gateway_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringArray) ProtoMessage() {}

func (x *StringArray) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringArray.ProtoReflect.Descriptor instead.
func (*StringArray) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_model_proto_rawDescGZIP(), []int{0}
}

func (x *StringArray) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type NatsGatewayRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Method        string                  `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Body          []byte                  `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Metadata      map[string]*StringArray `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NatsGatewayRequest) Reset() {
	*x = NatsGatewayRequest{}
	mi := &file_api_gateway_v1_gateway_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NatsGatewayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NatsGatewayRequest) ProtoMessage() {}

func (x *NatsGatewayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NatsGatewayRequest.ProtoReflect.Descriptor instead.
func (*NatsGatewayRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_model_proto_rawDescGZIP(), []int{1}
}

func (x *NatsGatewayRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *NatsGatewayRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *NatsGatewayRequest) GetMetadata() map[string]*StringArray {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type NatsGatewayResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Body          []byte                  `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Status        *status.Status          `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Metadata      map[string]*StringArray `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NatsGatewayResponse) Reset() {
	*x = NatsGatewayResponse{}
	mi := &file_api_gateway_v1_gateway_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NatsGatewayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NatsGatewayResponse) ProtoMessage() {}

func (x *NatsGatewayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NatsGatewayResponse.ProtoReflect.Descriptor instead.
func (*NatsGatewayResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_model_proto_rawDescGZIP(), []int{2}
}

func (x *NatsGatewayResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *NatsGatewayResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *NatsGatewayResponse) GetMetadata() map[string]*StringArray {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_api_gateway_v1_gateway_model_proto protoreflect.FileDescriptor

const file_api_gateway_v1_gateway_model_proto_rawDesc = "" +
	"\n" +
	"\"api/gateway/v1/gateway_model.proto\x12\x14hellforge.gateway.v1\x1a\x17google/rpc/status.proto\"#\n" +
	"\vStringArray\x12\x14\n" +
	"\x05items\x18\x01 \x03(\tR\x05items\"\xf4\x01\n" +
	"\x12NatsGatewayRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12R\n" +
	"\bmetadata\x18\x03 \x03(\v26.hellforge.gateway.v1.NatsGatewayRequest.MetadataEntryR\bmetadata\x1a^\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.hellforge.gateway.v1.StringArrayR\x05value:\x028\x01\"\x8a\x02\n" +
	"\x13NatsGatewayResponse\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\x12*\n" +
	"\x06status\x18\x02 \x01(\v2\x12.google.rpc.StatusR\x06status\x12S\n" +
	"\bmetadata\x18\x03 \x03(\v27.hellforge.gateway.v1.NatsGatewayResponse.MetadataEntryR\bmetadata\x1a^\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.hellforge.gateway.v1.StringArrayR\x05value:\x028\x01BAZ?github.com/DoomLordor/hellforge/pkg/proto/gateway/v1;gateway_v1b\x06proto3"

var (
	file_api_gateway_v1_gateway_model_proto_rawDescOnce sync.Once
	file_api_gateway_v1_gateway_model_proto_rawDescData []byte
)

func file_api_gateway_v1_gateway_model_proto_rawDescGZIP() []byte {
	file_api_gateway_v1_gateway_model_proto_rawDescOnce.Do(func() {
		file_api_gateway_v1_gateway_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_v1_gateway_model_proto_rawDesc), len(file_api_gateway_v1_gateway_model_proto_rawDesc)))
	})
	return file_api_gateway_v1_gateway_model_proto_rawDescData
}

var file_api_gateway_v1_gateway_model_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_gateway_v1_gateway_model_proto_goTypes = []any{
	(*StringArray)(nil),         // 0: hellforge.gateway.v1.StringArray
	(*NatsGatewayRequest)(nil),  // 1: hellforge.gateway.v1.NatsGatewayRequest
	(*NatsGatewayResponse)(nil), // 2: hellforge.gateway.v1.NatsGatewayResponse
	nil,                         // 3: hellforge.gateway.v1.NatsGatewayRequest.MetadataEntry
	nil,                         // 4: hellforge.gateway.v1.NatsGatewayResponse.MetadataEntry
	(*status.Status)(nil),       // 5: google.rpc.Status
}
var file_api_gateway_v1_gateway_model_proto_depIdxs = []int32{
	3, // 0: hellforge.gateway.v1.NatsGatewayRequest.metadata:type_name -> hellforge.gateway.v1.NatsGatewayRequest.MetadataEntry
	5, // 1: hellforge.gateway.v1.NatsGatewayResponse.status:type_name -> google.rpc.Status
	4, // 2: hellforge.gateway.v1.NatsGatewayResponse.metadata:type_name -> hellforge.gateway.v1.NatsGatewayResponse.MetadataEntry
	0, // 3: hellforge.gateway.v1.NatsGatewayRequest.MetadataEntry.value:type_name -> hellforge.gateway.v1.StringArray
	0, // 4: hellforge.gateway.v1.NatsGatewayResponse.MetadataEntry.value:type_name -> hellforge.gateway.v1.StringArray
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_gateway_v1_gateway_model_proto_init() }
func file_api_gateway_v1_gateway_model_proto_init() {
	if File_api_gateway_v1_gateway_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_v1_gateway_model_proto_rawDesc), len(file_api_gateway_v1_gateway_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_gateway_v1_gateway_model_proto_goTypes,
		DependencyIndexes: file_api_gateway_v1_gateway_model_proto_depIdxs,
		MessageInfos:      file_api_gateway_v1_gateway_model_proto_msgTypes,
	}.Build()
	File_api_gateway_v1_gateway_model_proto = out.File
	file_api_gateway_v1_gateway_model_proto_goTypes = nil
	file_api_gateway_v1_gateway_model_proto_depIdxs = nil
}
